version: 2

project_name: insti-attend-gsheets

before:
  hooks:
    - go mod tidy

builds:
  - flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  disable: true

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  disable: true
