services:
  iattend-gsheets:
    build: .
    image: arghyadipchak/insti-attend-gsheets:dev
    container_name: iattend-gsheets-dev
    restart: unless-stopped
    environment:
      USER_EMAIL: ${USER_EMAIL:-}
      USER_PASSWORD: ${USER_PASSWORD:-}
      TZ: Asia/Kolkata
    volumes:
      - ./data:/data
    ports:
      - 8090:8090
